name: Github Releases
description: Create a new release on GitHub with ghr
author: 'izumin5210'
inputs: 
  release-name:
    description: "Title of a release"
    default: ''
  release-body:
    description: "Description of a release"
    default: ''
  path:
    description: 'Path to artifacts'
    default: './dist'
  ghr-version:
    description: 'Version of github.com/tcnksm/ghr'
    default: 'v0.12.2'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.name }}
    - ${{ inputs.body }}
    - ${{ inputs.path }}
    - ${{ inputs.ghr-version }}
